### ISSUE TITLE
Licence?

### ISSUE THREAD

**Issue by dr-dimitru** [ccorcos/meteor-neo4j#6]
Hi @ccorcos ,
Under which licence code is maintained?

**Comment by ccorcos** [comment]
umm, well there are lots of open source contributions. but the core product
is privately owned.

**Comment by ccorcos** [comment]
this package? idk free and open source and i have no liability for your own personal use, but totally go use it, steal it, build on top of it, submit pull requests, all the goodness.

Neo4j themselves have their own licensing stuff. idk much about any of that honestly...

**Comment by dr-dimitru** [comment]
Thank you for reply, at least you may add copyleft to readme or somewhere else in this case

**Comment by ccorcos** [comment]
idk what any of that means ;)

**Comment by dr-dimitru** [comment]
> The copyright holders grant the freedom to copy, modify, convey, adapt, and/or redistribute this work ...

[ref](https://www.copyleft.org/guide/) and [copyleft.org](https://www.copyleft.org)
