### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by schabluk** [ccorcos/meteor-neo4j#8]
Hi,

I was trying to run the example and this is what I get on STDERR:

=> Started proxy.  
=> Started MongoDB.  
I20160110-19:00:11.124(1)? [http://localhost:7474/db/data/] neo4j connecting...
I20160110-19:00:11.126(1)? [http://localhost:7474/db/data/] neo4j connected
W20160110-19:00:11.126(1)? (STDERR) 
W20160110-19:00:11.126(1)? (STDERR) /Users/lusch/.meteor/packages/meteor-tool/.1.1.10.p2zb2e++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/fibers/future.js:245
W20160110-19:00:11.126(1)? (STDERR)                         throw(ex);
W20160110-19:00:11.126(1)? (STDERR)                               ^
W20160110-19:00:11.126(1)? (STDERR) TypeError: undefined is not a function
W20160110-19:00:11.127(1)? (STDERR)     at server/server.js:1:9
W20160110-19:00:11.127(1)? (STDERR)     at /Users/lusch/portfolio/fofoo/.meteor/local/build/programs/server/app/server/server.js:12:4
W20160110-19:00:11.127(1)? (STDERR)     at /Users/lusch/portfolio/fofoo/.meteor/local/build/programs/server/boot.js:242:10
W20160110-19:00:11.127(1)? (STDERR)     at Array.forEach (native)
W20160110-19:00:11.127(1)? (STDERR)     at Function._.each._.forEach (/Users/lusch/.meteor/packages/meteor-tool/.1.1.10.p2zb2e++os.osx.x86_64+web.browser+web.cordova/mt-os.osx.x86_64/dev_bundle/server-lib/node_modules/underscore/underscore.js:79:11)
W20160110-19:00:11.127(1)? (STDERR)     at /Users/lusch/portfolio/fofoo/.meteor/local/build/programs/server/boot.js:137:5
=> Exited with code: 8

My code is:
Neo4j = new Neo4jDB()

Did I missed something?

**Comment by ccorcos** [comment]
`Neo4jDb`

**Comment by schabluk** [comment]
I have ostrio:neo4jdriver installed, yet the error persists.
After removing ccorcos:neo4j the driver works fine.

**Comment by ccorcos** [comment]
Wrong package! Haha. They're fundamentally different approaches. ccorcos:neo4j is a very simple driver from running queries and when paired with ccorcos:any-db and ccorcos:any-store is a pretty generalize solution for using Neo4j. The package you mention would work well if your app is something like telescope and have a single curated query. But as soon as you start querying specific to each user, mongo will blow up. His also uses polling while anydb has a proactive refreshing mechanism.

**Comment by schabluk** [comment]
Ah, now I get it. I was confusing ccorcos:neo4j being a reactive observer over ostrio:neo4jdriver. I was using ostrio:neo4jreactivity but it has some bugs and limitations. Thank you.

**Comment by schabluk** [comment]
Ah, now I get it. I was confusing ccorcos:neo4j being a reactive observer over ostrio:neo4jdriver. I was using ostrio:neo4jreactivity but it has some bugs and limitations. Thank you.
